### ISSUE TITLE
Years column not start on correct row

### ISSUE THREAD

**Issue by commandiron** [lampione/ComposeCalendar#4]
<img src="https://user-images.githubusercontent.com/50905347/189750953-f6811dc8-8cc1-4031-a94a-218a5a2d1826.png" width="250" height="530">

Column should start row with current year.

**Comment by lampione** [comment]
Hello, can you put the calendar setup snippet you used here? Thank you

**Comment by commandiron** [comment]
Hello, sure;
```
ComposeCalendar(
    startDate = LocalDate.now(),
    minDate = LocalDate.MIN,
    maxDate = LocalDate.MAX,
    onDone = { it: LocalDate ->
        selectedDateMillis.value = it
        showDialog.value = false
    },
    onDismiss = { showDialog.value = false }
)
```

**Comment by lampione** [comment]
Fixed [HERE](https://github.com/lampione/ComposeCalendar/pull/6) Thank you for your help! I will shortly release version `1.0.2` with the fix.
