### ISSUE TITLE
Wrong month when passing own dates

### ISSUE THREAD

**Issue by Jalson1982** [lampione/ComposeCalendar#9]
Hello,
startDate: LocalDate = LocalDate.now().minusYears(16),

minDate: LocalDate = LocalDate.now().minusYears(90),

maxDate: LocalDate = LocalDate.now().minusYears(16),
 
When pass dates like this, I get one month less in my calendar so instead of october I get september 2006.

**Comment by lampione** [comment]
Fixed in #10 
This will be included in version 1.0.3 soon
Thank you!

**Comment by Jalson1982** [comment]
@lampione you have new bug. Try to send dates like this:
startDate: LocalDate =  1991-04-24

minDate: LocalDate = LocalDate.now().minusYears(90),

maxDate: LocalDate = LocalDate.now().minusYears(16)

You will see that you get this.

![Screenshot 2022-10-15 at 10 36 29](https://user-images.githubusercontent.com/35011526/195977486-674b59e1-6ace-4c00-a1ab-690eb8843c78.png)

**Comment by Jalson1982** [comment]
Basically if start date is different you always get October 1969

**Comment by lampione** [comment]
@Jalson1982 the second issue has been fixed in version 1.0.4 (#11) and will be soon available in maven. Thank you!
